In [2]:
import matplotlib.pyplot as plt
from matplotlib.patches import Ellipse
import sys

sys.path.append("../../../")
import numpy as np
from riemannian_geometry.computations.riemann_metric import LocalDiagPCA_Riemann
from riemannian_geometry.differential_geometry.curvature import batch_curvature
import torch
from utils.plotting.mesh import generate_lattice
from models.data.sklearn_datasets import MoonDataset, SpiralDataset, BlobsDataset, CirclesDataset


In [3]:
dataset = MoonDataset(1000, noise=0.05)

manifold = LocalDiagPCA_Riemann(dataset.X, sigma=0.05, rho=1e-3)

In [65]:
xy_grid = generate_lattice(dataset.X, 50)
g, dg, ddg = manifold.metric_tensor(xy_grid.transpose())

In [ ]:
N, D = xy_grid.shape

g_ = np.diag(g)

dg_ = np.zeros((N, D, D, D))
dg_[:, :, np.arange(D), np.arange(D)] = dg.transpose(0,2,1)

ddg_ = np.zeros((N, D, D, D, D))
ddg_[:, :, :, np.arange(D), np.arange(D)] = ddg.transpose(0,1,3,2) 

In [4]:
import numpy as np
import torch

a = np.random.randn(5, 2, 2)

b = torch.from_numpy(a).float()

vals, vectors = torch.linalg.eigh(b)
vals = vals.numpy()
vectors = vectors.numpy()
print(vectors)

vectors *= np.array([0.5, 10000])
print(vectors)


[[[-0.99830025 -0.05828169]
  [-0.05828169  0.99830025]]

 [[-0.73202866  0.68127376]
  [-0.68127376 -0.73202866]]

 [[-0.85523444 -0.51824135]
  [-0.51824135  0.85523444]]

 [[ 0.1634318  -0.9865546 ]
  [-0.9865546  -0.1634318 ]]

 [[-0.8904928  -0.45499736]
  [-0.45499736  0.8904928 ]]]
[[[-4.9915013e-01 -5.8281683e+02]
  [-2.9140843e-02  9.9830029e+03]]

 [[-3.6601433e-01  6.8127378e+03]
  [-3.4063688e-01 -7.3202866e+03]]

 [[-4.2761722e-01 -5.1824136e+03]
  [-2.5912067e-01  8.5523447e+03]]

 [[ 8.1715897e-02 -9.8655459e+03]
  [-4.9327731e-01 -1.6343180e+03]]

 [[-4.4524640e-01 -4.5499736e+03]
  [-2.2749868e-01  8.9049277e+03]]]
